services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  migrations:
    build: migrations
    command: -connectRetries=20 migrate
    environment:
      FLYWAY_USER: 'postgres'
      FLYWAY_MIXED: 'true'
      FLYWAY_PASSWORD: 'postgres'
      FLYWAY_URL: 'jdbc:postgresql://db:5432/postgres'
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
      - migrations
    volumes:
      - ./:/src
    links:
      - db
      - cache
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

volumes:
  db:
    driver: local
  cache:
    driver: local
